In [1]:
import torch

In [2]:
torch.__version__

'1.9.0'

In [3]:
import numpy as np

In [4]:
lst=[3,4,5,6]
arr=np.array(lst)


In [5]:
arr.dtype

dtype('int32')

In [6]:
###Convert numpy to pytorch tensor
tensors = torch.from_numpy(arr)
tensors

tensor([3, 4, 5, 6], dtype=torch.int32)

In [7]:
tensors[:2]

tensor([3, 4], dtype=torch.int32)

In [8]:
tensors[1:4]

tensor([4, 5, 6], dtype=torch.int32)

In [9]:
###disadvantange of from_numpy the array and tensor usage the same memory location
tensors[3] = 100

In [10]:
tensors

tensor([  3,   4,   5, 100], dtype=torch.int32)

In [11]:
arr

array([  3,   4,   5, 100])

In [12]:
### prevent this by using torch.tensor
tensor_arr=torch.tensor(arr)
tensor_arr

tensor([  3,   4,   5, 100], dtype=torch.int32)